#pragma once
#include <iostream>
#include <stdio.h>
#include <cstring>
#include <string>
#include <stdlib>
#include <cerrno>
#include <unistd.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/keysym.h>
#include <dpp/dpp.h>
#include "dotenv.h"
#include <thread>
#include <linux/input.h>
#include <fcntl.h>